// The room shell uses a small, local catalog. Security warnings are translated
// here with the same scope as the English source text.
export const english = {
  // --- B: landing, limits page, full-screen states (add keys here only) ---
  navLabel: "Site",
  navHow: "how",
  navLimits: "limits",
  navSource: "source",
  heroLineOne: "rooms that",
  heroLineTwo: "forget.",
  heroLede: "End-to-end encrypted in the browser. No account, no username, no server transcript. One invite per person, and the room destroys itself.",
  stripLabel: "At a glance",
  stripCipher: "cipher",
  stripKey: "key",
  stripFiles: "files",
  newRoom: "new room",
  vanishAfter: "messages vanish after",
  selfDestructAfter: "room self-destructs after idle",
  presetNever: "never",
  customDuration: "custom",
  createFootnote: "not independently audited · the relay sees connection metadata",
  readLimits: "read the limits",
  howTitle: "how it works",
  howCreateTitle: "create",
  howCreateCopy: "Pick how long messages last and when an idle room destroys itself. The room key is made in your browser and stays in the link's #fragment.",
  howInviteTitle: "send one invite",
  howInviteCopy: "Each invite admits one person, once, and then expires. Share it over a channel you already trust.",
  howDestroyTitle: "destroy",
  howDestroyCopy: "Hit destroy when you are done, or let the idle timer do it. There is no server transcript to hand over.",
  boxInvite: "invite",
  boxRoom: "room",
  backHomeShort: "back home",
  limitsTitle: "limits",
  limitsLede: "What this instance protects and what it cannot. Read this before you trust it with anything that matters.",
  limitsProtected: "what is protected",
  limitsProtectedEncryption: "Text and files are encrypted in your browser with AES-GCM before they leave it.",
  limitsProtectedKey: "The room key lives in the URL #fragment, which browsers never send to the server.",
  limitsProtectedSigned: "Peer events are signed with per-session keys, and room keys rotate when people join or leave.",
  limitsProtectedInvites: "Invites are single-use and expire.",
  limitsProtectedTranscript: "The server only relays ciphertext and keeps no transcript.",
  limitsProtectedTeardown: "When a room is destroyed or times out, its server state is torn down and everyone is disconnected.",
  limitsNotProtected: "what is not",
  limitsNotMetadata: "The relay still sees connection metadata: IP addresses, timing and message sizes.",
  limitsNotCopy: "Anyone in the room can copy, save or screenshot what they see.",
  limitsNotDevice: "A compromised browser, extension or device defeats all of this.",
  limitsNotAudit: "The code has not been independently audited.",
  limitsUpstream: "Based on the open-source elm.chat project, licensed AGPL-3.0.",
  limitsUpstreamLink: "upstream source",
  limitsSourceLink: "this instance's source",
  // --- end B ---
  minutes: "Minutes",
  hours: "Hours",
  days: "Days",
  indefinite: "Indefinite",
  messageDurationAmount: "Message vanish duration",
  messageDurationUnit: "Message vanish time unit",
  roomDurationAmount: "Room self-destruct duration",
  roomDurationUnit: "Room self-destruct time unit",
  onlyManualDestroy: "Only manual destroy",
  idle: "idle",
  createRoom: "Create private conversation",
  creatingRoom: "Creating room...",
  roomSecret: "Room secret stays in the URL fragment and never reaches the server.",
  messagesStay: "Messages stay until someone destroys the room.",
  messagesVanish: "Messages vanish after {duration}.",
  roomStays: "Room stays open until someone destroys it.",
  roomExpires: "Room self-destructs in {duration}.",
  destroyed: "This room was destroyed and everyone was disconnected.",
  joinTimeout: "This room self-destructed because nobody joined before the room timeout.",
  inactive: "This room self-destructed after the configured idle timeout.",
  maxAge: "This room reached its maximum lifetime and self-destructed.",
  unavailable: "This room is no longer available.",
  inviteClaimed: "This one-time invite is already being used by another browser session.",
  inviteUsed: "This one-time invite has already admitted another session.",
  inviteInvalid: "This one-time invite has expired, was revoked, or is no longer available.",
  invalidLink: "Link no longer valid",
  removedTitle: "You were removed from this room",
  removedCopy: "The room creator ended your access to this conversation.",
  checkingInvite: "Checking invite",
  verifyingInvite: "Verifying this one-time invite and joining the room.",
  roomGone: "Room gone",
  roomGoneCopy: "This conversation self-destructed. Nothing was kept.",
  roomNotFound: "This room no longer exists. It may have already self-destructed.",
  startNew: "Start a new one",
  connected: "Connected",
  connecting: "Connecting",
  securing: "Securing room keys…",
  disconnected: "Disconnected",
  retryConnection: "Retry connection",
  reconnecting: "Reconnecting in {seconds}s",
  closed: "Closed",
  connectionError: "Error",
  present: "{count} present",
  you: "You",
  guest: "Guest",
  waiting: "Waiting for someone to join.",
  remove: "Remove",
  newInviteExpires: "New invite expires",
  inviteNextOnly: "Applies only to the next single-use invite you create.",
  inviteLifetimeAmount: "Invite lifetime amount",
  inviteLifetimeUnit: "Invite lifetime unit",
  invites: "invites",
  inviteGuidance: "Send one unused invite to one person. Each link expires and can only be used once.",
  share: "Share",
  copyInvite: "Copy invite link",
  inviteShared: "Invite shared",
  inviteCopiedSend: "Invite copied, send it",
  sendInvite: "Send invite",
  inviteOne: "Invite one person",
  copied: "Copied",
  copyMyLink: "Copy my link",
  destroying: "Destroying...",
  destroy: "Destroy",
  inviteSharedStatus: "Invite shared.",
  inviteCopiedStatus: "Invite copied.",
  roomLinkCopiedStatus: "Room link copied.",
  deriving: "Deriving key and joining room...",
  download: "Download",
  downloadFileLabel: "Download {name}",
  fileCardLabel: "File {name}",
  saveFileLabel: "Save file {name}",
  fileProgressLabel: "File transfer progress for {name}",
  transferFailed: "Transfer failed: ask for a re-share",
  attachFile: "Attach an encrypted file",
  attachFileLabel: "Attach file",
  writeMessageLabel: "Write an encrypted message",
  conversationLog: "Encrypted conversation",
  findConversation: "Find in conversation",
  hideConversation: "Hide conversation",
  showConversation: "Show conversation",
  conversationHidden: "Conversation hidden",
  concealmentHint: "This only hides this screen. Anyone using this browser can reveal it.",
  findVisibleMessages: "Search visible messages",
  findHint: "Search messages still in this conversation.",
  findNoMatches: "No matches in visible messages",
  findMatchCount: "{count} matching messages",
  findPosition: "Message {position} of {count}",
  findPrevious: "Previous match",
  findNext: "Next match",
  findClose: "Close search",
  jumpToLatest: "Jump to latest",
  newMessagesJump: "New messages: {count} · Jump to latest",
  writeMessage: "Write a message",
  roomClosed: "Room is closed",
  sendEncrypted: "Send encrypted",
  authFailed: "Message authentication failed. Check that you opened the full capability link.",
  alteredMessage: "Unsupported or altered message was rejected.",
  replayLimit: "This page reached its message limit. Open a new room to continue.",
  syncEmpty: "No connected peer had recent messages to share. The server keeps no transcript.",
  syncPartial: "Recent messages were supplied by a peer; this is not a complete server-backed history.",
  syncTruncated: "A peer supplied the latest 200 messages. Earlier history may be unavailable.",
  copiedInviteNotice: "Invite copied. Send it to one person: the link can only be used once.",
  sharedInviteNotice: "Invite handed to your selected app. The link can only be used once.",
  createdInviteNotice: "Invite created. Choose Share or Copy below when you are ready.",
  removedInviteNotice: "Invite removed.",
  inviteStatusRevoked: "revoked",
  inviteStatusJoined: "joined",
  inviteStatusJoining: "joining...",
  inviteStatusExpired: "expired",
  inviteStatusExpires: "expires in {duration}",
  peerDestroyed: "A connected peer destroyed this room.",
  fileTooLarge: "\"{name}\" is larger than the {limit} limit.",
  fileDeliveryPending: "File shared locally, but delivery to other participants is not ready yet.",
  fileRequestFailed: "Could not reach the sender to start the download.",
  missingSecret: "Missing room secret in the URL fragment.",
  messageSendFailed: "Message was not sent. Your draft is still here. Try again.",
  clipboardLinkFailed: "Clipboard access is blocked in this browser context. Copy the link manually from the address bar.",
  manualInviteLabel: "Invite link for manual copying",
  manualInviteHelp: "Select the link and copy it using your browser or keyboard. Send it only to the person you want to invite.",
  dismissManualInvite: "Hide invite link",
  createInviteFailed: "Failed to create invite.",
  revokeInviteFailed: "Failed to revoke invite.",
  destroyRoomFailed: "Failed to destroy room.",
  inviteShareText: "Join my disposable chat room. This single-use link expires.",
  vanishesIn: "Vanishes in {duration}",
  untilRoomCloses: "Available until the room closes",
  participants: "Participants",
  inviteExpiration: "Invite expiration",
  access: "Access",
  unableCreateRoom: "Unable to create room.",
  failedCreateRoom: "Failed to create room.",
  failedLoadInvites: "Failed to load invites.",
  failedJoinRoom: "Failed to join room.",
  // --- C: room (add keys here only) ---
  roomBoxTitle: "room",
  messagesBoxTitle: "messages",
  hiddenBoxTitle: "hidden",
  vanishShort: "vanish",
  vanishOff: "off",
  endsShort: "ends",
  endsManual: "on destroy",
  findShort: "find",
  hideShort: "hide",
  fileTag: "file",
  fileGet: "get",
  fileSave: "save",
  fileSharedNote: "shared, peers can download",
  composerAttach: "+file",
  sendShort: "send",
  // --- end C ---
} as const;

export type MessageKey = keyof typeof english;
export type Locale = "en" | "es";

export const spanish: Record<MessageKey, string> = {
  // --- B: landing, limits page, full-screen states (add keys here only) ---
  navLabel: "Sitio",
  navHow: "cómo",
  navLimits: "límites",
  navSource: "código",
  heroLineOne: "salas que",
  heroLineTwo: "olvidan.",
  heroLede: "Cifrado de extremo a extremo en el navegador. Sin cuenta, sin nombre de usuario, sin transcripción en el servidor. Una invitación por persona, y la sala se destruye sola.",
  stripLabel: "De un vistazo",
  stripCipher: "cifrado",
  stripKey: "clave",
  stripFiles: "archivos",
  newRoom: "nueva sala",
  vanishAfter: "los mensajes desaparecen tras",
  selfDestructAfter: "la sala se destruye tras inactividad de",
  presetNever: "nunca",
  customDuration: "otro",
  createFootnote: "sin auditoría independiente · el servidor de retransmisión ve metadatos de conexión",
  readLimits: "lee los límites",
  howTitle: "cómo funciona",
  howCreateTitle: "crea",
  howCreateCopy: "Elige cuánto duran los mensajes y cuándo se destruye una sala inactiva. La clave de la sala se genera en tu navegador y se queda en el #fragmento del enlace.",
  howInviteTitle: "envía una invitación",
  howInviteCopy: "Cada invitación deja entrar a una sola persona, una sola vez, y luego caduca. Compártela por un canal en el que ya confíes.",
  howDestroyTitle: "destruye",
  howDestroyCopy: "Pulsa destruir cuando termines o deja que lo haga el temporizador de inactividad. No hay transcripción en el servidor que entregar.",
  boxInvite: "invitación",
  boxRoom: "sala",
  backHomeShort: "volver al inicio",
  limitsTitle: "límites",
  limitsLede: "Qué protege esta instancia y qué no puede proteger. Léelo antes de confiarle algo importante.",
  limitsProtected: "qué está protegido",
  limitsProtectedEncryption: "Los textos y archivos se cifran en tu navegador con AES-GCM antes de salir de él.",
  limitsProtectedKey: "La clave de la sala vive en el #fragmento de la URL, que los navegadores nunca envían al servidor.",
  limitsProtectedSigned: "Los eventos entre participantes se firman con claves de cada sesión, y las claves de la sala rotan cuando alguien entra o sale.",
  limitsProtectedInvites: "Las invitaciones son de un solo uso y caducan.",
  limitsProtectedTranscript: "El servidor solo retransmite texto cifrado y no guarda ninguna transcripción.",
  limitsProtectedTeardown: "Cuando una sala se destruye o caduca, su estado en el servidor se elimina y todos quedan desconectados.",
  limitsNotProtected: "qué no lo está",
  limitsNotMetadata: "El servidor de retransmisión sigue viendo metadatos de conexión: direcciones IP, horarios y tamaños de los mensajes.",
  limitsNotCopy: "Cualquiera en la sala puede copiar, guardar o hacer capturas de lo que ve.",
  limitsNotDevice: "Un navegador, una extensión o un dispositivo comprometido anula todo esto.",
  limitsNotAudit: "El código no ha pasado una auditoría independiente.",
  limitsUpstream: "Basado en el proyecto de código abierto elm.chat, con licencia AGPL-3.0.",
  limitsUpstreamLink: "código original",
  limitsSourceLink: "código de esta instancia",
  // --- end B ---
  minutes: "Minutos",
  hours: "Horas",
  days: "Días",
  indefinite: "Indefinido",
  messageDurationAmount: "Tiempo hasta que desaparecen los mensajes",
  messageDurationUnit: "Unidad de tiempo hasta que desaparecen los mensajes",
  roomDurationAmount: "Tiempo hasta la autodestrucción de la sala",
  roomDurationUnit: "Unidad de tiempo hasta la autodestrucción de la sala",
  onlyManualDestroy: "Solo destrucción manual",
  idle: "de inactividad",
  createRoom: "Crear conversación privada",
  creatingRoom: "Creando sala...",
  roomSecret: "El secreto de la sala permanece en el fragmento de la URL y nunca llega al servidor.",
  messagesStay: "Los mensajes permanecen hasta que alguien destruye la sala.",
  messagesVanish: "Los mensajes desaparecen después de {duration}.",
  roomStays: "La sala permanece abierta hasta que alguien la destruye.",
  roomExpires: "La sala se autodestruye en {duration}.",
  destroyed: "Esta sala se destruyó y todas las personas fueron desconectadas.",
  joinTimeout: "Esta sala se autodestruyó porque nadie entró antes de que venciera el plazo.",
  inactive: "Esta sala se autodestruyó tras el periodo de inactividad configurado.",
  maxAge: "Esta sala alcanzó su duración máxima y se autodestruyó.",
  unavailable: "Esta sala ya no está disponible.",
  inviteClaimed: "Otra sesión del navegador ya está usando esta invitación de un solo uso.",
  inviteUsed: "Esta invitación de un solo uso ya permitió entrar a otra sesión.",
  inviteInvalid: "Esta invitación de un solo uso caducó, fue revocada o ya no está disponible.",
  invalidLink: "El enlace ya no es válido",
  removedTitle: "Se te ha retirado de esta sala",
  removedCopy: "Quien creó la sala canceló tu acceso a esta conversación.",
  checkingInvite: "Comprobando invitación",
  verifyingInvite: "Verificando esta invitación de un solo uso y entrando en la sala.",
  roomGone: "Sala desaparecida",
  roomGoneCopy: "Esta conversación se autodestruyó. No se conservó nada.",
  roomNotFound: "Esta sala ya no existe. Es posible que ya se haya autodestruido.",
  startNew: "Iniciar otra",
  connected: "Conectado",
  connecting: "Conectando",
  securing: "Protegiendo las claves de la sala…",
  disconnected: "Desconectado",
  retryConnection: "Reintentar conexión",
  reconnecting: "Reconectando en {seconds}s",
  closed: "Cerrado",
  connectionError: "Error",
  present: "{count} presentes",
  you: "Tú",
  guest: "Invitado",
  waiting: "Esperando a que alguien entre.",
  remove: "Eliminar",
  newInviteExpires: "La nueva invitación caduca",
  inviteNextOnly: "Se aplica solo a la próxima invitación de un solo uso que crees.",
  inviteLifetimeAmount: "Duración de la invitación",
  inviteLifetimeUnit: "Unidad de duración de la invitación",
  invites: "invitaciones",
  inviteGuidance: "Envía una invitación sin usar a una sola persona. Cada enlace caduca y solo puede usarse una vez.",
  share: "Compartir",
  copyInvite: "Copiar enlace de invitación",
  inviteShared: "Invitación compartida",
  inviteCopiedSend: "Invitación copiada: envíala",
  sendInvite: "Enviar invitación",
  inviteOne: "Invitar a una persona",
  copied: "Copiado",
  copyMyLink: "Copiar mi enlace",
  destroying: "Destruyendo...",
  destroy: "Destruir",
  inviteSharedStatus: "Invitación compartida.",
  inviteCopiedStatus: "Invitación copiada.",
  roomLinkCopiedStatus: "Enlace de la sala copiado.",
  deriving: "Derivando la clave y entrando en la sala...",
  download: "Descargar",
  downloadFileLabel: "Descargar {name}",
  fileCardLabel: "Archivo {name}",
  saveFileLabel: "Guardar archivo {name}",
  fileProgressLabel: "Progreso de transferencia de {name}",
  transferFailed: "Transferencia fallida: pide que lo compartan de nuevo",
  attachFile: "Adjuntar un archivo cifrado",
  attachFileLabel: "Adjuntar archivo",
  writeMessageLabel: "Escribir un mensaje cifrado",
  conversationLog: "Conversación cifrada",
  findConversation: "Buscar en la conversación",
  hideConversation: "Ocultar conversación",
  showConversation: "Mostrar conversación",
  conversationHidden: "Conversación oculta",
  concealmentHint: "Esto solo oculta esta pantalla. Cualquier persona que use este navegador puede mostrarla.",
  findVisibleMessages: "Buscar mensajes visibles",
  findHint: "Busca mensajes que aún están en esta conversación.",
  findNoMatches: "Sin coincidencias en los mensajes visibles",
  findMatchCount: "{count} mensajes coincidentes",
  findPosition: "Mensaje {position} de {count}",
  findPrevious: "Coincidencia anterior",
  findNext: "Siguiente coincidencia",
  findClose: "Cerrar búsqueda",
  jumpToLatest: "Ir a los últimos mensajes",
  newMessagesJump: "Mensajes nuevos: {count} · Ir a los últimos",
  writeMessage: "Escribe un mensaje",
  roomClosed: "La sala está cerrada",
  sendEncrypted: "Enviar cifrado",
  authFailed: "Falló la autenticación del mensaje. Comprueba que abriste el enlace completo.",
  alteredMessage: "Se rechazó un mensaje no compatible o alterado.",
  replayLimit: "Esta página alcanzó el límite de mensajes. Abre una sala nueva para continuar.",
  syncEmpty: "Ningún participante conectado tenía mensajes recientes para compartir. El servidor no guarda una transcripción.",
  syncPartial: "Un participante compartió mensajes recientes; no es un historial completo respaldado por el servidor.",
  syncTruncated: "Un participante compartió los últimos 200 mensajes. Es posible que el historial anterior no esté disponible.",
  copiedInviteNotice: "Invitación copiada. Envíala a una persona: el enlace solo puede usarse una vez.",
  sharedInviteNotice: "Invitación enviada a la aplicación elegida. El enlace solo puede usarse una vez.",
  createdInviteNotice: "Invitación creada. Elige Compartir o Copiar cuando quieras.",
  removedInviteNotice: "Invitación eliminada.",
  inviteStatusRevoked: "revocada",
  inviteStatusJoined: "usada",
  inviteStatusJoining: "entrando...",
  inviteStatusExpired: "caducada",
  inviteStatusExpires: "caduca en {duration}",
  peerDestroyed: "Una persona conectada destruyó esta sala.",
  fileTooLarge: "\"{name}\" supera el límite de {limit}.",
  fileDeliveryPending: "El archivo se compartió localmente, pero aún no se puede entregar a otras personas.",
  fileRequestFailed: "No se pudo contactar a quien envió el archivo para iniciar la descarga.",
  missingSecret: "Falta el secreto de la sala en el fragmento de la URL.",
  messageSendFailed: "No se envió el mensaje. Tu borrador sigue aquí. Inténtalo de nuevo.",
  clipboardLinkFailed: "El portapapeles está bloqueado en este navegador. Copia el enlace desde la barra de direcciones.",
  manualInviteLabel: "Enlace de invitación para copiar manualmente",
  manualInviteHelp: "Selecciona el enlace y cópialo con el navegador o el teclado. Envíalo solo a la persona que quieres invitar.",
  dismissManualInvite: "Ocultar enlace de invitación",
  createInviteFailed: "No se pudo crear la invitación.",
  revokeInviteFailed: "No se pudo revocar la invitación.",
  destroyRoomFailed: "No se pudo destruir la sala.",
  inviteShareText: "Entra en mi sala de chat temporal. Este enlace de un solo uso caduca.",
  vanishesIn: "Desaparece en {duration}",
  untilRoomCloses: "Disponible hasta que se cierre la sala",
  participants: "Participantes",
  inviteExpiration: "Caducidad de la invitación",
  access: "Acceso",
  unableCreateRoom: "No se pudo crear la sala.",
  failedCreateRoom: "No se pudo crear la sala.",
  failedLoadInvites: "No se pudieron cargar las invitaciones.",
  failedJoinRoom: "No se pudo entrar en la sala.",
  // --- C: room (add keys here only) ---
  roomBoxTitle: "sala",
  messagesBoxTitle: "mensajes",
  hiddenBoxTitle: "oculta",
  vanishShort: "desaparecen",
  vanishOff: "nunca",
  endsShort: "termina",
  endsManual: "al destruirla",
  findShort: "buscar",
  hideShort: "ocultar",
  fileTag: "archivo",
  fileGet: "bajar",
  fileSave: "guardar",
  fileSharedNote: "compartido, otros pueden descargarlo",
  composerAttach: "+archivo",
  sendShort: "enviar",
  // --- end C ---
};

export function resolveLocale(languages: readonly string[]): Locale {
  for (const language of languages) {
    const code = language.toLowerCase().split("-")[0];
    if (code === "es") return "es";
    if (code === "en") return "en";
  }
  return "en";
}

export function translate(
  locale: Locale,
  key: MessageKey,
  values: Record<string, string | number> = {}
): string {
  const template = locale === "es" ? spanish[key] : english[key];
  return template.replace(/\{(\w+)\}/g, (_, name: string) => String(values[name] ?? `{${name}}`));
}

export const locale = resolveLocale(
  typeof navigator === "undefined" ? [] : navigator.languages.length ? navigator.languages : [navigator.language]
);
export const t = (key: MessageKey, values?: Record<string, string | number>) =>
  translate(locale, key, values);
